# Generated by Django 5.0.2 on 2024-02-29 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='Название')),
                ('text', models.TextField(blank=True, verbose_name='Текст пасты')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paste.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Паста',
                'verbose_name_plural': 'Пасты',
            },
        ),
    ]
